### ISSUE TITLE
Create integration example (angular)

### ISSUE THREAD

**Issue by remojansen** [inversify/inversify-code-samples#4]
Should be based on

https://github.com/tastejs/todomvc/tree/gh-pages/examples/angularjs_require

**Comment by AlexPalma72** [comment]
Hi @remojansen, I really like inversify, I started an angularjs 1.4 typescript project and would like to use inversify with it so I would have my typescript classes clean, for any changes you have the angular js example almost ready r can you point mei n the right direction.

TIA
