### ISSUE TITLE
breaks in Chrome

### ISSUE THREAD

**Issue by jmp909** [inversify/inversify-code-samples#5]
using chrome, on the example site http://inversify.io/inversify-code-samples/marionette/ (& also my local build at localhost:8080) I get these errors... consistently on my local build, occasionally on the inversify.io site

`/inversify-code-samples/marionette/node_modules/jquery/dist/jquery.js?bust=1454076599641:8556 
Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.`

`/inversify-code-samples/marionette/node_modules/backbone.marionette/lib/backbone.marionette.js?bust=1454076599641:2884 Uncaught ChildViewContainerMissingError: The specified "childViewContainer" was not found: #todo-list`

firefox & IE on my local build seem to be ok.

thanks for any advice
J

**Comment by remojansen** [comment]
Hi @jmp909 are those errors causing the example to stop working or are they just warnings? The error is cause by the usage of synchronous ajax calls in a few files:

[header_layout.ts](https://github.com/inversify/inversify-code-samples/blob/ccd7e4b3f1a66acf5eb26c7356e450a3aa0742e2/marionette/source/layout/header_layout.ts#L23)
[footer_layout.ts](https://github.com/inversify/inversify-code-samples/blob/ccd7e4b3f1a66acf5eb26c7356e450a3aa0742e2/marionette/source/layout/footer_layout.ts#L43)
[todo_item_view.ts](https://github.com/inversify/inversify-code-samples/blob/ccd7e4b3f1a66acf5eb26c7356e450a3aa0742e2/marionette/source/views/todo_item_view.ts#L30)

This error is not part of InversifyJS and can be solved [doing asynchronous ajax calls](http://stackoverflow.com/questions/11507244/backbone-marionette-async-modular-template-loading).

**Comment by jmp909** [comment]
It's not working. I see some of the UI and I can type in a todo but it doesn't get added. Also the footer section is blank , whereas in Firefox/IE I can see text there.

I'm using latest Chrome on Windows 10 if that helps.  

Thanks
J

**Comment by jmp909** [comment]
actually sometimes it doesn't load at all...
![blank-ui](https://cloud.githubusercontent.com/assets/2184982/12699240/292283e4-c7ac-11e5-86f1-a18f98a16551.jpg)

**Comment by jmp909** [comment]
on localhost, I've just realised they are getting added as `<li class="active"></li>` but they are empty.

hope this helps

regards
j
![ui-local](https://cloud.githubusercontent.com/assets/2184982/12699258/be4e73ba-c7ac-11e5-8915-617d5db9749b.jpg)

**Comment by remojansen** [comment]
It looks like I did something wrong  with the marionette API. I'm reopening the issue just to make sure that is not caused by InversifyJS. Thanks for reporting :wink:
